USE [student]
GO

SELECT [A_SessionID]
      ,[SemesterID]
      ,[CourseCode]
      ,[CourseId]
      ,[ContinuosAssesment]
      ,[Exam]
      ,[Score]
      ,[Grade]
      ,[CourseUnit]
      ,[ProgrammeID]
      ,[LevelID]
      ,[MatricNo]
      ,[CPoint]
      ,[SemID]
      ,[DateCreated]
      ,[TimeCreated]
      ,[AStatus]
      ,[ProgrammeTypeID]
      ,[ProgrammeID2]
      ,[DeptId]
      ,[RegistrationID]
  FROM [dbo].[registration]
GO

