# Generated by Django 3.1.6 on 2021-02-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voiceregistration',
            options={'managed': False},
        ),
    ]
