# Generated by Django 3.1.6 on 2021-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': False,
            },
        ),
    ]
